# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Viktor Platz
tagline:          'Personal Website'
description:      'Welcome to my personal website.'
url:              https://redviktor.github.io/
baseurl:          ""

author:
  name:           'Viktor Platz'
  url:            https://twitter.com/Redviktor10

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
